name: Test Build Setup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Verify files
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo ""
        echo "=== Main.py exists? ==="
        ls -la main.py || echo "main.py NOT FOUND"
        echo ""
        echo "=== Buildozer.spec exists? ==="
        ls -la buildozer.spec || echo "buildozer.spec NOT FOUND"
        echo ""
        echo "=== Requirements.txt exists? ==="
        ls -la requirements.txt || echo "requirements.txt NOT FOUND"
        echo ""
        echo "=== Python version ==="
        python --version
        echo ""
        echo "=== Pip version ==="
        pip --version
    
    - name: Install buildozer
      run: |
        echo "=== Installing buildozer ==="
        python -m pip install --upgrade pip
        pip install buildozer
        buildozer --version
    
    - name: Validate buildozer.spec
      run: |
        echo "=== Validating buildozer.spec ==="
        buildozer --help
        echo "Buildozer spec validation completed"
    
    - name: Test Summary
      run: |
        echo "🎉 All basic tests passed!"
        echo "✅ Python setup working"
        echo "✅ Files are present"
        echo "✅ Buildozer installs correctly"
        echo ""
        echo "Ready to proceed with full APK build!"
